CREATE TABLE AM_APP_KEY_DOMAIN_MAPPING (
CONSUMER_KEY VARCHAR(255),
AUTHZ_DOMAIN VARCHAR(255) DEFAULT 'ALL',
PRIMARY KEY (CONSUMER_KEY,AUTHZ_DOMAIN),
FOREIGN KEY (CONSUMER_KEY) REFERENCES IDN_OAUTH_CONSUMER_APPS(CONSUMER_KEY)
)ENGINE INNODB;

INSERT INTO AM_APP_KEY_DOMAIN_MAPPING(CONSUMER_KEY,AUTHZ_DOMAIN)
SELECT CONSUMER_KEY, "ALL" as new_val
FROM IDN_OAUTH_CONSUMER_APPS;

ALTER TABLE `AM_APPLICATION` ADD COLUMN `CALLBACK_URL` VARCHAR(512)  AFTER `APPLICATION_TIER`;

ALTER TABLE AM_SUBSCRIPTION  ADD SUB_STATUS VARCHAR(50) DEFAULT 'UNBLOCKED' NOT NULL
